services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: proyecto-gallo-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "GalloPassword_2026!"
      MSSQL_PID: "Developer"
    ports:
      - "3301:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  sqlserver_data:
